trigger:
  - main
  
stages:
  - stage: Build
    displayName: Build stage
    pool:
      name: Default
      demands:
          - dotnet
          - JETBRAINS_RESHARPER_GLOBALTOOLS -equals 2025.3.0
    variables:
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    jobs:
      - job: Build_Solution
        displayName: Whole solution build process
        steps:
        - task: DotNetCoreCLI@2
          displayName: 'Build solution ShoppingApp.slnx'
          inputs:
            command: build
            projects: 'ShoppingApp.slnx'
            configuration: '$(buildConfiguration)'
        - task: CmdLine@2
          displayName: 'Inspect Code with ReSharper CLI'
          inputs:
            script: |
              export PATH=$PATH:/resharpercli
              jb inspectcode ShoppingApp.slnx --no-build -f="Html;Xml" --profile="ShoppingApp.sln.DotSettings" -o="inspect-code-output" --properties:Configuration=$(buildConfiguration)
        - task: PowerShell@2
          displayName: 'Analyze ReSharper CLI Results'
          inputs:
            targetType: filePath
            filePath: ./AnalyzeReSharperCLIResults.ps1