trigger:
  - main
  
stages:
  - stage: Build
    displayName: Build stage
    pool:
      name: Default
      demands:
          - dotnet
    variables:
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    jobs:
      - job: Build_Solution
        displayName: Whole solution build process
        steps:
        - task: DotNetCoreCLI@2
          displayName: 'Build solution ShoppingApp.slnx'
          inputs:
            command: build
            projects: 'ShoppingApp.slnx'
            configuration: '$(buildConfiguration)'
  
        # Run Tests
        - task: DotNetCoreCLI@2
          displayName: 'Run Integration Tests'
          inputs:
            command: test
            projects: |
              test/ShoppingApp.Tests
              test/ShoppingApp.Tests.FSharp
            publishTestResults: true